# Generated by Django 5.1.7 on 2025-03-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_category_delete_productcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("1", "菓子パン"),
                    ("2", "食パン"),
                    ("3", "ブレッド他"),
                    ("4", "惣菜・デニ"),
                    ("5", "ドーナツ"),
                    ("6", "常温サンド"),
                    ("7", "冷蔵サンド"),
                    ("8", "その他"),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
