# Generated by Django 5.1.7 on 2025-03-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
